module.exports = {
  src: "./src",
  language: "typescript",
  schema: "./src/graphql/schema.graphql",
  schemaExtensions: ["./src/graphql/"],
  eagerEsModules: true,
  customScalars: {
    uuid: "string",
    int8: "string",
    bigint: "string",
    numeric: "number",
    varbit: "string",
    bit: "string",
    char: "string",
    varchar: "string",
    bool: "boolean",
    int: "number",
    int4: "number",
    float8: "number",
    timestamptz: "string",
    timetz: "string",
    jsonb: "Record<string, unknown>",
    _text: "string",
    text: "string",
    date: "string",
    time: "string",
  },
};
