import {
  FOOD_TYPES_DOCUMENT,
  ADD_FOOD_TYPE_DOCUMENT,
  DELETE_FOOD_TYPE_DOCUMENT,
  UPDATE_FOOD_TYPE_DOCUMENT,
} from "./FoodTypes";

export {
  FOOD_TYPES_DOCUMENT,
  ADD_FOOD_TYPE_DOCUMENT,
  DELETE_FOOD_TYPE_DOCUMENT,
  UPDATE_FOOD_TYPE_DOCUMENT,
};
