export const FB_APP_ID = import.meta.env.VITE_FACEBOOK_APP_ID;
export const EMAILJS_SERVICE_ID = import.meta.env.VITE_EMAILJS_SERVICE_ID || "";
export const EMAILJS_USER_ID = import.meta.env.VITE_EMAILJS_USER_ID || "";
export const EMAILJS_RESET_PASSWORD_TEMPLATE_ID =
    import.meta.env.VITE_EMAILJS_RESET_PASSWORD_TEMPLATE_ID || "";
export const EMAILJS_REGISTRATION_CONFIRMATION_TEMPLATE_ID =
    import.meta.env.VITE_EMAILJS_REGISTRATION_CONFIRMATION_TEMPLATE_ID || "";
